zone:
	name: "libreswan.org."
	zonefile: "/etc/nsd/zones/libreswan.org.signed"
zone:
	name: "testing.libreswan.org."
	zonefile: "/etc/nsd/zones/testing.libreswan.org.signed"
zone:
	name: "0.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/0.192.in-addr.arpa.signed"
zone:
	name: "1.0.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/1.0.192.in-addr.arpa.signed"
zone:
	name: "1.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/1.192.in-addr.arpa.signed"
zone:
	name: "192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/192.in-addr.arpa.signed"
zone:
	name: "2.0.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/2.0.192.in-addr.arpa.signed"
zone:
	name: "2.1.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/2.1.192.in-addr.arpa.signed"
zone:
	name: "3.0.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/3.0.192.in-addr.arpa.signed"
zone:
	name: "3.1.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/3.1.192.in-addr.arpa.signed"
zone:
	name: "4.1.192.in-addr.arpa."
	zonefile: "/etc/nsd/zones/4.1.192.in-addr.arpa.signed"
